#!/bin/bash -e
cd -- "$(dirname "$0")"

echo "This script will remove the Dune Dynasty app bundle from macOS quarantine."
read -n1 -s -r -p $'Press (y)es to continue or any other key to exit...\n' key

if [ "$key" = 'y' ]; then
    xattr -r -d com.apple.quarantine Dune\ Dynasty.app
    echo "All finished..."
else
    echo "Exiting without doing anything..."
fi