#ifndef TABLE_SOUND_H
#define TABLE_SOUND_H

#include "types.h"

/** Number of voices in the game. */
#define NUM_VOICES 131

/** Maximal number of spoken audio fragments in one message. */
#define NUM_SPEECH_PARTS 5

enum SampleID {
	SAMPLE_SCREAM1 = 0,
	SAMPLE_EXPLODE_SAND = 1,
	SAMPLE_ROCKET = 2,
	SAMPLE_BUTTON = 3,
	SAMPLE_SCREAM5 = 4,
	SAMPLE_STRUCTURE_DESTROYED = 5,
	SAMPLE_EXPLODE_SMALL = 6,
	SAMPLE_EXPLODE_MEDIUM = 7,
	SAMPLE_EXPLODE_LARGE = 8,
	SAMPLE_EXPLODE_CANNON = 9,
	SAMPLE_MACHINE_GUN = 10,
	SAMPLE_GUN = 11,
	SAMPLE_EXPLODE_GAS = 12,
	SAMPLE_PLACEMENT = 13,
	SAMPLE_SCREAM2 = 14,
	SAMPLE_SCREAM3 = 15,
	SAMPLE_SCREAM4 = 16,
	SAMPLE_AFFIRMATIVE = 17,
	SAMPLE_YES_SIR = 18,
	SAMPLE_REPORTING = 19,
	SAMPLE_ACKNOWLEDGED = 20,
	SAMPLE_INFANTRY_OUT = 21,
	SAMPLE_MOVING_OUT = 22,
	SAMPLE_COME_TO_POPPA = 23, /* unused */
	SAMPLE_SOMETHINGS_UNDER_THE_SAND = 24, /* unused */
	SAMPLE_RADAR_STATIC = 25,
	SAMPLE_SANDWORM = 26,
	SAMPLE_MINI_ROCKET = 27,
	SAMPLE_SQUISH = 28,

	SAMPLE_VOICE_FRAGMENT_ENEMY = 29,
	SAMPLE_VOICE_FRAGMENT_HARKONNEN = 30,
	SAMPLE_VOICE_FRAGMENT_ATREIDES = 31,
	SAMPLE_VOICE_FRAGMENT_ORDOS = 32,
	SAMPLE_VOICE_FRAGMENT_FREMEN = 33,
	SAMPLE_VOICE_FRAGMENT_SARDAUKAR = 34,
	SAMPLE_VOICE_FRAGMENT_MERCENARY = 35, /* silent */
	SAMPLE_VOICE_FRAGMENT_UNIT = 36,
	SAMPLE_VOICE_FRAGMENT_STRUCTURE = 37,
	SAMPLE_VOICE_FRAGMENT_ONE = 38,
	SAMPLE_VOICE_FRAGMENT_TWO = 39,
	SAMPLE_VOICE_FRAGMENT_THREE = 40,
	SAMPLE_VOICE_FRAGMENT_FOUR = 41,
	SAMPLE_VOICE_FRAGMENT_FIVE = 42,
	SAMPLE_VOICE_FRAGMENT_CONSTRUCTION_COMPLETE = 43,
	SAMPLE_VOICE_FRAGMENT_RADAR = 44,
	SAMPLE_VOICE_FRAGMENT_DEACTIVATED = 45,
	SAMPLE_VOICE_FRAGMENT_ACTIVATED = 46,
	SAMPLE_VOICE_FRAGMENT_FRIGATE = 47,
	SAMPLE_VOICE_FRAGMENT_HAS_ARRIVED = 48,
	SAMPLE_VOICE_FRAGMENT_WARNING = 49,
	SAMPLE_VOICE_FRAGMENT_SABOTEUR = 50,
	SAMPLE_VOICE_FRAGMENT_MISSILE = 51,
	SAMPLE_VOICE_FRAGMENT_SPICE_BLOOM = 52,
	SAMPLE_VOICE_FRAGMENT_DESTROYED = 53,
	SAMPLE_VOICE_FRAGMENT_DEPLOYED = 54,
	SAMPLE_VOICE_FRAGMENT_APPROACHING = 55,
	SAMPLE_VOICE_FRAGMENT_LOCATED = 56,
	SAMPLE_VOICE_FRAGMENT_FROM_THE_NORTH = 57,
	SAMPLE_VOICE_FRAGMENT_FROM_THE_EAST = 58,
	SAMPLE_VOICE_FRAGMENT_FROM_THE_SOUTH = 59,
	SAMPLE_VOICE_FRAGMENT_FROM_THE_WEST = 60,
	SAMPLE_VOICE_FRAGMENT_YOUR_MISSION_IS_COMPLETE = 61,
	SAMPLE_VOICE_FRAGMENT_YOU_HAVE_FAILED_YOUR_MISSION = 62,
	SAMPLE_VOICE_FRAGMENT_LAUNCHED = 63,
	SAMPLE_VOICE_FRAGMENT_OUR_BASE_IS_UNDER_ATTACK = 64,
	SAMPLE_VOICE_FRAGMENT_VEHICLE = 65,
	SAMPLE_VOICE_FRAGMENT_REPAIRED = 66,
	SAMPLE_VOICE_FRAGMENT_HARVESTER = 67,
	SAMPLE_VOICE_FRAGMENT_WORM_SIGN = 68,
	SAMPLE_VOICE_FRAGMENT_CAPTURED = 69,
	SAMPLE_VOICE_FRAGMENT_SELECT = 70,
	SAMPLE_VOICE_FRAGMENT_YOUR_NEXT_CONQUEST = 71,

	SAMPLE_BLASTER = 72, /* Harkonnen end game. */
	SAMPLE_GLASS = 73, /* Harkonnen end game. */
	SAMPLE_LIZARD = 74, /* Ordos end game. */
	SAMPLE_FLESH = 75, /* Harkonnen end game. */
	SAMPLE_CLICK = 76, /* Harkonnen end game. */

	/* Intro movie sounds, values [77, 119]. */
	SAMPLE_INTRO_DUNE = 87,
	SAMPLE_INTRO_THE_BUILDING = 82,
	SAMPLE_INTRO_OF_A_DYNASTY = 88,
	SAMPLE_INTRO_THE_PLANET_ARRAKIS = 111,
	SAMPLE_INTRO_KNOWN_AS_DUNE = 105,
	SAMPLE_INTRO_LAND_OF_SAND = 114,
	SAMPLE_INTRO_HOME = 101,
	SAMPLE_INTRO_OF_THE_SPICE = 115,
	SAMPLE_INTRO_MELANGE = 106,
	SAMPLE_INTRO_THE_SPICE = 116,
	SAMPLE_INTRO_CONTROLS = 86,
	SAMPLE_INTRO_THE_EMPIRE = 93,
	SAMPLE_INTRO_WHOEVER = 118,
	SAMPLE_INTRO_CONTROLS_DUNE = 83,
	SAMPLE_INTRO_CONTROLS_THE_SPICE = 84,
	SAMPLE_INTRO_THE_EMPEROR = 104,
	SAMPLE_INTRO_HAS_PROPOSED_A_CHALLENGE = 113,
	SAMPLE_INTRO_TO_EACH_OF_THE_HOUSES = 89,
	SAMPLE_INTRO_THE_HOUSE = 92,
	SAMPLE_INTRO_THAT_PRODUCES = 94,
	SAMPLE_INTRO_THE_MOST_SPICE = 97,
	SAMPLE_INTRO_WILL_CONTROL_DUNE = 91,
	SAMPLE_INTRO_THERE_ARE_NO_SET = 98,
	SAMPLE_INTRO_TERRITORIES = 96,
	SAMPLE_INTRO_AND_NO = 90,
	SAMPLE_INTRO_RULES_OF_ENGAGEMENT = 95,
	SAMPLE_INTRO_VAST_ARMIES = 117,
	SAMPLE_INTRO_HAVE_ARRIVED = 79,
	SAMPLE_INTRO_AND_NOW = 78,
	SAMPLE_INTRO_THREE_HOUSES_FIGHT = 77,
	SAMPLE_INTRO_FOR_CONTROL = 85,
	SAMPLE_INTRO_OF_DUNE = 109,
	SAMPLE_INTRO_THE_NOBLE_ATREIDES = 107,
	SAMPLE_INTRO_THE_INSIDIOUS = 103,
	SAMPLE_INTRO_ORDOS = 110,
	SAMPLE_INTRO_AND_THE = 99,
	SAMPLE_INTRO_EVIL_HARKONNEN = 100,
	SAMPLE_INTRO_ONLY_ONE_HOUSE = 102,
	SAMPLE_INTRO_WILL_PREVAIL = 112,
	SAMPLE_INTRO_YOUR = 119,
	SAMPLE_INTRO_BATTLE_FOR_DUNE = 80,
	SAMPLE_INTRO_BEGINS = 81,
	SAMPLE_INTRO_NOW = 108,

	SAMPLE_120 = 120,
	SAMPLE_DROP_LOAD = 121,
	SAMPLE_EXPLODE_TINY = 122,

	SAMPLE_INTRO_WIND = 123,
	SAMPLE_INTRO_HARVESTER = 124,
	SAMPLE_INTRO_FIRE_ORNITHOPTER_TROOPER = 125,
	SAMPLE_INTRO_BREAK_GLASS = 126,
	SAMPLE_INTRO_FIRE_LAUNCHER = 127,
	SAMPLE_INTRO_CARRYALL_FRIGATE = 128,
	SAMPLE_INTRO_TROOPER_EXPLODE1 = 129,
	SAMPLE_INTRO_TROOPER_EXPLODE2 = 130,

	SAMPLEID_MAX = 131,
	SAMPLE_INVALID = 0xFFFF
};

/** Information about sound files. */
typedef struct SoundData {
	const char *string; /*!< Pointer to a string. */
	uint16 variable_04; /*!< ?? */
} SoundData;

/** Audio and visual feedback about events and commands. */
typedef struct Feedback {
	uint16 voiceId[NUM_SPEECH_PARTS]; /*!< English spoken text. */
	uint16 messageId;                 /*!< Message to display in the viewport when audio is disabled. */
	uint16 soundId;                   /*!< Sound. */
} Feedback;

extern const SoundData g_table_voices[SAMPLEID_MAX];
extern const SoundData g_table_musics[];
extern const uint16 g_table_voiceMapping[];
extern const Feedback g_feedback[];
extern const uint16 g_translatedVoice[][NUM_SPEECH_PARTS];

#endif
